http.host: 0.0.0.0
# 跨域配置
http.cors.enabled: true
http.cors.allow-origin: "*"

path.logs: /usr/share/elasticsearch/logs
# path.plugins: /usr/share/elasticsearch/plugins
path.repo: /tmp/es_backup

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
