language: bash

script:
- make build_tar_gz

    
notifications:
  email:
    recipients:
    - charlessoft@qq.com
    on_success: never
    on_failure: always

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: ./**/*.tar.gz
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master


