version: "3"

services:
  app:
    image: matomo
    restart: always
    volumes:
#     - ./config:/var/www/html/config
#     - ./logs:/var/www/html/logs
      - ${PWD}/matomo/html:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=117.78.19.194
      - TZ=Asia/Shanghai
    env_file:
      - ./db.env
    ports:
      - 127.0.0.1:18089:80  # 8080可以更改为别的未使用的端口  lsof -i:8080 可以查看8080端口是否被使用
      - 127.0.0.1:8443:443 # 8443可以更改为别的未使用的端口  这边后续填到NPM的“Custom location”里
volumes:
  db:
  matomo:

