version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root       #初始化管理员用户名和密码
      - MONGO_INITDB_ROOT_PASSWORD=123456
    tty: true
volumes:
  dbdata6:

