name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - shell: bash
        run: |
          make build_tar_gz
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload tar.gz files
        uses: actions/upload-artifact@v2
        with:
          name: tarball-artifacts
          path: |
              *.tar.gz
      - run: echo "job's status is ${{ job.status }}."

